### ISSUE TITLE
Is there some way to annotate values that I don't want in my default values.yaml?

### ISSUE THREAD

**Issue by red8888** [norwoodj/helm-docs#110]
I suppose it is a best practice to have ALL possible values of your template have some default value set, but sometimes it is not possible.

For example take this value (which comes from the default template helm generates for you)

```
podSecurityContext: {}
  # fsGroup: 2000
```

podSecurityContext is using toYaml but I also want to be able to notate examples of specific configs under it (like fsGroup for example).

Is there some way to comment out a value AND also have helm docs add it to the readme?

Another example from the default template:
```
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
```

Thanks!

**Comment by danrspencer** [comment]
I do this by supplying `null` for any values that I want in the `values.yaml` but there isn't a sensible default that can be provided. In conjunction with `values.schema.json` you can then force them to be supplied at install time.

**Comment by red8888** [comment]
I recently discovered helm 3 supports json schema ootb and it looks like there are a few tools that can generate markdown from json schema. So I think I might approach helm documentation generation via json schemas (using the "description" field) along with some tool that can generate markdown from json schema.
