### ISSUE TITLE
bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by hrodrig** [norwoodj/helm-docs#115]
```
% brew upgrade helm-docs
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the norwoodj/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/norwoodj/homebrew-tap/Formula/helm-docs.rb:9

```

**Comment by steinbrueckri** [comment]
Just for reference https://github.com/norwoodj/homebrew-tap/pull/2

**Comment by sagikazarmark** [comment]
I think that's a good quick fix, but keep in mind that the formula is generated, so tagging a new release should also fix the problem (CI apparently always uses the latest goreleaser and it's already fixed there)

**Comment by utkuozdemir** [comment]
Just bump goreleaser version to >=v0.183.0 and make a new release - it solves the problem. See the changelog: https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0

**Comment by sagikazarmark** [comment]
No need, CI already uses the latest.

**Comment by mstrzele** [comment]
@sagikazarmark so... correct me if I'm wrong, but it's a matter of waiting for a new version of `helm-docs` to be released, isn't it? CI will use the latest version of `goreleaser` and will remove `bottle :unneeded` from formulae.

**Comment by sagikazarmark** [comment]
Correct

**Comment by yermulnik** [comment]
Any plans on when this becomes a reality?
```
==> Installing helm-docs from norwoodj/tap
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the norwoodj/tap tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/norwoodj/homebrew-tap/Formula/helm-docs.rb:9
```

**Comment by yermulnik** [comment]
Yay 🥳 
![image](https://user-images.githubusercontent.com/1274789/150221152-8e3c12a5-0204-481f-a865-4ababa7bc0c1.png)

**Comment by mstrzele** [comment]
@hrodrig wanna close the issue?
