### ISSUE TITLE
add option to ignore subcharts

### ISSUE THREAD

**Issue by knackaron** [norwoodj/helm-docs#12]
When subcharts are part of a Git repo and are only included for distribution (e.g., subchart as a Git submodule), helm-docs should have an option to ignore rendering docs for subcharts.

Example of undesirable behavior:
```
$ git submodule status
 e074e59e9b42fce856b029265d9ccc0163d22f13 charts/subchart2 (2019.0.0-1-ge074e59)
 f91a918ebc2ea969bfbcda884c57b7d8f83f45b2 charts/subchart1 (2019.0.2)

$ helm-docs
INFO[2019-08-05T17:55:03-04:00] Found Chart directories [., charts/subchart2, charts/subchart1] 
INFO[2019-08-05T17:55:03-04:00] Generating README Documentation for chart charts/subchart1  
INFO[2019-08-05T17:55:03-04:00] Generating README Documentation for chart .  
INFO[2019-08-05T17:55:03-04:00] Generating README Documentation for chart charts/subchart2 

$ git st
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

    modified:   README.md
    modified:   charts/subchart2 (modified content)
    modified:   charts/subchart1 (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by sc250024** [comment]
@knackaron Can I ask why you're using Git submodules in your `charts/` directory? That seems to go against the whole workflow of the `helm dependency` command, as well as the point of the `requirements.yaml` and `requirements.lock` files in the first place.

**Comment by knackaron** [comment]
> @knackaron Can I ask why you're using Git submodules in your charts/ directory? That seems to go against the whole workflow of the helm dependency command, as well as the point of the requirements.yaml and requirements.lock files in the first place.

We maintain a large number of private charts, of which many helper charts and subcharts are included across the primary charts and umbrella charts.  We found that maintaining chart dependencies as Git submodules to be better to keep everything in the Git workflow, versus relying on Helm's native dependency management and pulling in external artifacts from chart repositories.  It also ensures portability of the charts in deployments where chart repositories are not available (e.g., isolated networks).

A public example of a large Helm chart that is equally complex as some of ours and that doesn't use Helm's dependency management is GitLab's chart: https://gitlab.com/charts/gitlab/tree/master/charts

**Comment by RothAndrew** [comment]
Yeah, but, they should. GitLab's chart is confusing as hell, partly because it doesn't follow the standard convention of Helm's chart dependency system.

**Comment by knackaron** [comment]
Opened a MR with the functionality I'm looking for.  It doesn't affect the default behavior.

**Comment by sc250024** [comment]
I'm learn towards @RothAndrew 's point, but if it's a use case, why not? Up to @norwoodj in the end.

**Comment by norwoodj** [comment]
Hey, sorry I have been so slow on the response. I looked at your PR and I'm not sure if this is exactly the approach I want to go with. Thank you for the feature request, as it forced me to do something I have been meaning to do a long time.

See the PR I'll attach, it will add a `.helmdocsignore` file that can be used like a `.gitignore` file to exclude directories from processing. This way you can accomplish what you're going for, not having to supply the ignore-dir option everytime. It is also more flexible, in my opinion.

**Comment by knackaron** [comment]
@norwoodj Thanks.  That solution is superior and will work great for us.
