### ISSUE TITLE
helm-docs write extra empty line

### ISSUE THREAD

**Issue by jlec** [norwoodj/helm-docs#177]
I tried to find the right place in the code but wasn't able to determine what is causing it.

To reproduce, just run `helm-docs` against this repo. All the generated `README.md` have 2 empty lines.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/79732/229484154-0dcbf05b-1872-4064-bdc9-193b36e88727.png">

**Comment by jlec** [comment]
Actually the fix was simple -> #178

**Comment by Nepo26** [comment]
It doesn't look like a bug. Can you remember why did you end the README with 2 lines @Artus-LHIND ?

If it doesn't break any formatting or tests for me it's okay to change it. But I propose you a new fix @jlec.

**Comment by jlec** [comment]
If you run any standard formatter against a file with 2 trailing empty lines, it will be reformatted. Which in turn means, that validation of format will bail out.
