### ISSUE TITLE
Q&A - Auto sorting

### ISSUE THREAD

**Issue by shyam-ks** [norwoodj/helm-docs#179]
Is there a way to stop the auto-sorting based on alphabets ?

if the keys are like 

Rabc
Zabc
Cabc

it should keep the same order in the readme generated

**Comment by losil** [comment]
Try to use the parameter `--sort-values-order file` for e.g.:

```shell
helm-docs --sort-values-order file
```

This option should consider the order coming from your `values.yaml` file when generating the table.

**Comment by shyam-ks** [comment]
> --sort-values-order

Awesome Thank you
