### ISSUE TITLE
v1.11.1 does not have a release

### ISSUE THREAD

**Issue by morremeyer** [norwoodj/helm-docs#187]
Hey everyone!

I noted that v1.11.1 was tagged, but does not have a release associated. Is v1.11.1 to be considered unreleased or will there not be GitHub releases anymore in the future?
Depending on the plans here, we'll need to update our dependency management configuration, that's why I'm asking.

**Comment by Nepo26** [comment]
Hey, it'll be released. Sorry by the unconvinience there was a problem with the release that I'm working on.

You can expect to have a release still. I will fix it soon.

**Comment by morremeyer** [comment]
No worries! Just wanted to know. 

Thank you for the work ♥️
