### ISSUE TITLE
@latest produces different files than last release (1.11.0), missing a newline at the end of file

### ISSUE THREAD

**Issue by stefanandres** [norwoodj/helm-docs#189]
Hey,
we recently noticed that one of the last commits since the last release changes the behavior of having a newline at the end of the generated file.

Since most markdown linters complain about missing newlines (https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md047.md) I think it would be best to have them.

I couldn't find the commit responsible for this, nor any configuration to specify the explicit behavior.

How can we force it to have newlines with the latest code?

## 1.11.0
```
root@14f226924d8b:/helm-docs# go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.11.0
root@14f226924d8b:/helm-docs# /home/runner/go/bin/helm-docs --chart-search-root=charts/istio/
INFO[2023-08-01T11:59:46Z] Found Chart directories [istio-1.17.3]
INFO[2023-08-01T11:59:46Z] Generating README Documentation for chart charts/istio/istio-1.17.3
root@14f226924d8b:/helm-docs# cat -A charts/istio/istio-1.17.3/README.md|tail -n 1
| kiali.tunnelCname | string | `""` | The DNS name at which the Cloudflare tunnel to the cluster is available. |$
root@14f226924d8b:/helm-docs#
```

## latest
```
root@14f226924d8b:/helm-docs# go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
root@14f226924d8b:/helm-docs# /home/runner/go/bin/helm-docs --chart-search-root=charts/istio/
INFO[2023-08-01T11:57:50Z] Found Chart directories [istio-1.17.3]
INFO[2023-08-01T11:57:50Z] Generating README Documentation for chart charts/istio/istio-1.17.3
root@14f226924d8b:/helm-docs# cat -A charts/istio/istio-1.17.3/README.md|tail -n 1
| kiali.tunnelCname | string | `""` | The DNS name at which the Cloudflare tunnel to the cluster is available. |root@14f226924d8b:/helm-docs# 
```

**Comment by Nepo26** [comment]
Hey, sorry by the late response. 

As this probably was a problem related from a minor change, it was just reverted and a new tag was pushed. 

If you can confirm if it's working as expected for you.

**Comment by Nepo26** [comment]
As there was no comment, I'm assuming that everything is ok. Closing the issue.
