### ISSUE TITLE
Add support for sections and custom introduction

### ISSUE THREAD

**Issue by kirankumar-grootan** [norwoodj/helm-docs#193]
Add support for the section just like bitnami readme generator where parameters can be broken down into sub-parameters using @section keyword 
https://github.com/bitnami/charts/blob/main/bitnami/redis/README.md

This will be helpful to separate DB sections, common values sections etc

**Comment by Nepo26** [comment]
Hey @kirankumar-grootan. Great suggestion, this can make things be better and more modular.

---

@Haepaxlog I'll look into your PR as soon as possible. If I see any problem, I'll ping you.

Hey there! Your PR looks promising, and I appreciate your contribution. I'll dive into it as soon as I can. If I come across anything that needs attention or have any questions, I'll be sure to reach out to you. Thanks again for your work on this!

**Comment by a-devops-guy** [comment]
Hi @Nepo26 May I know what help is need to develop this feature. Let me see what I can do from my end.
