### ISSUE TITLE
Missing versions in GitHub Releases

### ISSUE THREAD

**Issue by mjasion** [norwoodj/helm-docs#196]
On [dockerhub](https://hub.docker.com/r/jnorwood/helm-docs/tags) `latests` tags points to [`v1.11.2`](https://hub.docker.com/layers/jnorwood/helm-docs/v1.11.2/images/sha256-a6acbe60214074c5b8eee3f7f052ec9d33c3aeccf4e2d35bd660308a10336d8b?context=explore) version. 

[GitHub Releases](https://github.com/norwoodj/helm-docs/releases) latest release is `v1.11.0`. 

Can I ask you to release versions, pinned to correct commits?

**Comment by Nepo26** [comment]
Hey @mjasion. I'm aware of this issue. Currently, there is a problem with releasing versions. Thank you for pointing this out, and it makes sense to ask to update.

**Comment by Nepo26** [comment]
Hey @mjasion. We just fixed the problem with releasing version. Are you able to confirm that everything in ok?

**Comment by ebuildy** [comment]
Looks like the brew recipe is missing the version again:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/h/helm-docs.rb
