### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by brettmorien** [norwoodj/helm-docs#197]
Hi there. Our security tools are uncovering some vulnerabilities in older versions of some go libraries that helm-docs is importing. Specifically the spf13/viper library 1.4.0 includes references to grpc-middleware which has some exposure around grpc.

I have run a `go get -u ./...` against the repo to update all the dependencies to their latest. The make still works correctly, and dropping the binary into our tooling generates no different output docs.

Can you do a dependency update pass and release? If it helps I can push a PR with the changes.

**Comment by Nepo26** [comment]
Hi @brettmorien. Thanks for bringing this to my attention. I'll take a look at your PR and the dependency update. Currently, I'm dealing with some version publishing issues, but I aim to review and merge your changes within the next two weeks. Your contribution is much appreciated!

**Comment by norwoodj** [comment]
Merged the PR

**Comment by brettmorien** [comment]
Thank you for pulling this into the trunk. Are you planning to tag a release with this update soon?
