### ISSUE TITLE
Array of scalars is hard to document

### ISSUE THREAD

**Issue by halkeye** [norwoodj/helm-docs#20]
In my freshrss chart, I have an array of minutes for a cronjob to run, which by default is 23 and 53

```
freshrss:
  # freshrss.cron_min - What minutes of the hour should the cron script run
  cron_min: [23, 53]
```

produces

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| freshrss.cron_min[0] | int | `23` |  |
| freshrss.cron_min[1] | int | `53` |  |

Is there a way to tell it to document the entire array not the specific entries in the array?

**Comment by norwoodj** [comment]
Hey @halkeye, improved behavior for this was actually recently implemented in [v0.5.0](https://github.com/norwoodj/helm-docs/releases/tag/v0.5.0). You should upgrade or install helm-docs with homebrew:
```
brew upgrade norwoodj/tap/helm-docs

# Or if you haven't installed with brew before:
brew install norwoodj/tap/helm-docs
```

It actually looks like you might have the newer version though, and the comment you have there should cause the list itself to be documented, your comment is just formatted wrong:

```
-  # freshrss.cron_min - What minutes of the hour should the cron script run
+  # freshrss.cron_min -- What minutes of the hour should the cron script run
```

If you add a second dash to the comment you have and make sure you have the newest version of helm-docs, this should produce:

```
Key | Type | Default | Description
-- | -- | -- | --
freshrss.cron_min | list | `[23,53]` |  What minutes of the hour should the cron script run |

**Comment by halkeye** [comment]
yay the double dash fixed it!

i tried to scour any docs and stuff to find it

**Comment by norwoodj** [comment]
Glad to hear it! Closing this issue
