### ISSUE TITLE
bug: Binary artifacts renamed in `v1.11.2`

### ISSUE THREAD

**Issue by stevehipwell** [norwoodj/helm-docs#200]
The [v1.11.2 release](https://github.com/norwoodj/helm-docs/releases/tag/v1.11.2) included a breaking change to the naming of the artifacts which resulted in failed automation where the name was relied on to be stable. A change of this magnitude should really have been accompanied by a major version change, but at the minimum I'd expect it to have been a minor version change with accompanying documentation.

Was this an intentional change or a result of the release issues covered in #196? If this was intentional could the release notes be updated to show the change and if it wasn't are you planning on reverting the changes?

**Comment by Nepo26** [comment]
Hey @stevehipwell seems like this was a mistake on our side when updating the goreleaser. 
It seems to have been introduced by these commits:
- https://github.com/norwoodj/helm-docs/commit/915324471b55c50d4f6038ff0423676e3649206b
- https://github.com/norwoodj/helm-docs/commit/297d05b88f00cf987d7faf7bfc413d6933243bef
- https://github.com/norwoodj/helm-docs/commit/d94c81190a2d70584432741589ae17e607a224e8


The following comment went unnoticed by us on the [deprecation notice](https://goreleaser.com/deprecations/#archivesreplacements):
> Notice that if you are using the archives.name_template, notice it also has a {{.Version}} in it. Adjust the new name_template accordingly.


I will fix it and then release this version again. Thank you for making us aware of the issue!

**Comment by stevehipwell** [comment]
@Nepo26 it might be better to fix it in a patch release?

**Comment by Nepo26** [comment]
You say to guarantee everyone gets the update?

**Comment by stevehipwell** [comment]
> You say to guarantee everyone gets the update?

@Nepo26 yes, and because I'm personally aware of a number of places which have been modified to work with the current latest release and will as such need this change undoing.

**Comment by viceice** [comment]
Any plans to change the file names back to the old schema? Or do we need to adapt our scripts to use the new schema?

**Comment by Nepo26** [comment]
Yes, I'm changing back the names in this current week.

**Comment by stevehipwell** [comment]
I'll update Scoop again to use the correct name format (I updated it for the last release).
