### ISSUE TITLE
[Feat]: recursive with template from root (and template inside chart)

### ISSUE THREAD

**Issue by wrenix** [norwoodj/helm-docs#205]
### General Summary

Current the README.md.gotmpl is not used in root-directory if it is not an helm-chart.

so the following does not work:
```
- README.md.gotmpl
- chart-1/
  - Chart.yaml
```

### Is your feature request related to a problem? Please describe and/or link to a bug issue.

read from ROOT also the templates

### Expected Behavior

is templates with given README.md.gotmpl

### Current Behavior

used internal default README.md.gotmpl

### Alternatives you've considered

i need my own "recursive", function:
```
for chart in *; do
  cd $chart && helm-docs -t ../README.md.gotmpl && cd -;
done
```

### Further Information

Maybe it is also nice to have an mix, like templates files in chart-folder and root-folder e.g.:
```
- docs-tmpl/
   - flower.gotmpl
   - README.md.gotmpl
- chart1/
  - docs-tmpl/
    - rose.gotmpl
  - Chart.yaml
```

**Comment by norwoodj** [comment]
Hey @wrenix, I believe I'm understanding your issue correctly, and that this is already possible. The key text is [here](https://github.com/norwoodj/helm-docs#markdown-rendering):
```
If a template file is specified as a filename only as with the default above, the file is interpreted as being relative to each chart directory found. If however a template file is specified as a relative path, e.g. the first of --template-files=./_templates.gotmpl --template-files=README.md.gotmpl then the file is interpreted as being relative to the chart-search-root.
```

So, for the example you provided in the general summary:
```
- README.md.gotmpl
- chart-1/
  - Chart.yaml
```

If you ran `helm-docs` in the root of this repository, you could accomplish what you're attempting with:
```
helm-docs --template-files=./README.md.gotmpl
```

In the more complicated example you provide after, it is also possible, but you cannot put the `rose.gotmpl` file in a subdirectory of the chart, it can only be in the root of the chart. If you put it there, however it's possible e.g.:

```
$ ls -R
.:
chart1  docs-tmpl

./chart1:
Chart.yaml  README.md  README.md.gotmpl  requirements.yaml  rose.gotmpl  values.yaml

./docs-tmpl:
flower.gotmpl
```

Then run helm-docs like this:
```
../helm-docs --template-files=README.md.gotmpl --template-files=rose.gotmpl --template-files=./docs-tmpl/flower.gotmpl
```
