### ISSUE TITLE
Including docs for subcharts

### ISSUE THREAD

**Issue by sc250024** [norwoodj/helm-docs#21]
@norwoodj This is a feature request / conversational issue. In a sense, it's the opposite of the https://github.com/norwoodj/helm-docs/issues/12 issue filed by @knackaron.

How easy / difficult would it be to _also_ document subcharts defined in the `requirements.yaml` file ? I know that typically this is not done. However, I'm in the process of writing a common Helm chart, and being able to document the common chart's `values.yaml` file, but include it in a parent chart, would be useful.

What do you think?

**Comment by norwoodj** [comment]
I apologize @sc250024 I've been out of the country the last two weeks without a computer.

I'm not sure exactly what you mean, so you'd have to give me an example. Do you want the values from sub-charts to be captured in the README for the parent chart? I suppose that we could add a new command line option that would enable this behavior, but you'd have to answer a few questions regarding this feature:

* What values from the sub-charts are documented? Just the ones overridden in the parent values.yaml file? All of them?
* Which sub-charts are documented? Is it all or none? Can we specify that the names of particular sub-charts that should have their values documented?

I think an example of what you're trying to do would help me understand a bit. Definitely not opposed to adding a feature like this, I'm just not quite understanding the functionality you're describing.
