### ISSUE TITLE
[Bug]: `helm-docs.versionFooter` missing when installing tool using Go

### ISSUE THREAD

**Issue by juanjjaramillo** [norwoodj/helm-docs#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing the tool using Go:
```shell
go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
```
the field `helm-docs.versionFooter` is missing and it is not rendered in the documentation

### Expected Behavior

Field `helm-docs.versionFooter` should be defined and rendered in the documentation

### Reference Chart

https://github.com/juanjjaramillo/testbed/tree/main/charts/testbed

### Reference Template

{{ template "helm-docs.versionFooter" . }}

### Environment

- Operating system: Ubuntu 22.04.4 LTS
- Helm version (output of `helm version`): version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.22.0"}
- GO version (output of `go version`): go1.22.0
- Method of calling `helm-docs` (manual, jenkins, github action ...): GitHub action with following script
```
# Run first actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
helm-docs
```

### Further Information

Easy way to disable problem is not to use `helm-docs.versionFooter` at all, but I hope I can continue giving credit to this amazing project

**Comment by norwoodj** [comment]
Not a bug, it's that the version isn't set when you install this way. I've investigated if it would be possible to do this, but I haven't found a way to set build arguments as part of the build that is run when you run `go install`.
