### ISSUE TITLE
[Bug]: Release tag missing `v` prefix

### ISSUE THREAD

**Issue by stevehipwell** [norwoodj/helm-docs#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest release tag is `1.14.0` which is breaking automation which expects a `v` prefix.

### Expected Behavior

I'd expect the latest release tag to be `v1.14.0`.

### Reference Chart

N/A

### Environment

- Operating system:
- Helm version (output of `helm version`):
- GO version (output of `go version`):
- Method of calling `helm-docs` (manual, jenkins, github action ...):

**Comment by stevehipwell** [comment]
- [Scoop failure](https://github.com/ScoopInstaller/Main/actions/runs/9836132481/job/27151197862#step:3:520)

**Comment by mpepping** [comment]
Came here to say this

**Comment by stevehipwell** [comment]
@norwoodj FYI this issue is blocking automation which relies on the tag structure to retrieve the latest version of `helm-docs`.

**Comment by stevehipwell** [comment]
@norwoodj the same issue is present for [1.14.1](https://github.com/norwoodj/helm-docs/releases/tag/1.14.1) release.

**Comment by norwoodj** [comment]
Dammit, sorry haven't released this in a while and I don't have a check for this in the release script

**Comment by stevehipwell** [comment]
@norwoodj if you add a `v` prefix to the release GH Actions workflow it's only run for a valid tag.

```yaml
name: Release

on:
  push:
    tags:
      - v*
```

**Comment by stevehipwell** [comment]
My suggestion would be to release `v1.14.0` & `v1.14.1` off the same commits as the non `v` prefixed versions. I would then update the description of the incorrect releases to say as much. And finally I'd release `v1.14.2` to make sure that there is no ambiguity on the correct release format. Would you like a PR to make the above change to be used as the commit for a `v1.14.2` release?

**Comment by norwoodj** [comment]
Hey @stevehipwell. I'm sorry about the mistake, I'm an idiot. I have re-released those tags with the correct format, and will release a v1.14.2 like you suggest with some new checks in both the github action and release script.

**Comment by stevehipwell** [comment]
Thanks for the quick response @norwoodj.

On a related topic I've noticed that the current GitHub actions workflows use sliding tag based references, would you be interested in a PR to switch these over to the recommended deterministic SHA based pattern (e.g. `uses: actions/checkout@v4` -> `uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7`)? Dependabot works correctly with this pattern to keep them up to date so there is minimal additional overhead for a significant increase in both security and reporoducability.

**Comment by mpepping** [comment]
> Hey @stevehipwell. I'm sorry about the mistake, I'm an idiot. I have re-released those tags with the correct format, and will release a v1.14.2 like you suggest with some new checks in both the github action and release script.

Thanks for the quick fix, @norwoodj! .. Rest assured that these kinds of mistakes never happy to any of us reading along here 😉

**Comment by norwoodj** [comment]
Let me know if there are any other problems with the tagging, I believe the fixes I just made should correct things.

**Comment by stevehipwell** [comment]
@norwoodj the new tags look to be working correctly. I've created https://github.com/norwoodj/helm-docs/pull/253 to update the GH Actions.
