### ISSUE TITLE
Feature: Configuration file for various text snippets

### ISSUE THREAD

**Issue by estahn** [norwoodj/helm-docs#26]
I have created a `README.md.gotmpl` that follows the official helm charts repo more closely, e.g. [README.md](https://github.com/helm/charts/blob/master/stable/nginx-ingress/README.md).

Unfortunately, not all information is present in the `Chart.yml` and therefore it's usually required to add more details to the README.md. This will then make it hard to update the `README.md` through helm-docs upon changes in the helm chart.

It would be great to have the ability to regenerate the `README.md` upon changes.

I suggest having a `helm-docs` configuration file, e.g. `.helm-docs.yaml` which can be located in each chart repo with relevant text snippets to be added to the final `README.md`.

**Example:**
`README.md.gotmpl`:
```
# {{ .Name }}

helm install {{ .cfg.ChartRepository }}/{{ .Name }}

{{ .cfg.SomeRandomText }}
```

`.helm-docs.yaml`:
```
ChartRepository: mychartrepo
SomeRandomText: |
  Lorem Ipsum
```

**Comment by norwoodj** [comment]
Hey @estahn. Thanks for taking the time to open this issue. I'm not entirely sure what the use case here is, unfortunately. Is the idea that you might want to repeat these snippets, like `.cfg.ChartRepository` many times in your README.md.gotmpl file? At present I don't see the value in factoring these values out into a separate file when what you've described above could be accomplished with the following README.md.gotmpl:
```
# {{ .Name }}

helm install mychartrepo/{{ .Name }}

Lorem Ipsum
```

**Comment by norwoodj** [comment]
@estahn, I'm still thinking that this is a _lot_ of added complexity for a use case that I don't think is helpful enough to justify this. I'm going to close this for now, but feel free to re-open if you disagree.

**Comment by estahn** [comment]
@norwoodj Sorry for the late response. The reason for this was to keep the `README.md.gotmpl` the same across multiple projects/teams. We would have a single `README.md.gotmpl` that multiple projects/teams can pull in from a single location. The current helm/charts/stable repo is (arguably) a good example of keeping READMEs consistent across charts.

However, I can see how this becomes messy with lots of custom information a chart possibly requires.

An alternative I can think of using a similar approach to most TOC plugins with placeholders, `<!-- toc --> ... <!-- tocstop -->` for the values table for example.

https://github.com/estahn/cloudping/blame/master/README.md#L13-L24
