### ISSUE TITLE
Feature: allow for custom name of generated files

### ISSUE THREAD

**Issue by raphstrebel** [norwoodj/helm-docs#28]
Hey! 
Would it be possible to include a flag to specify a new name for the generated markdown files ? :) I didn't find a way to change the names to something other than "README.md", and some other readme's of the project I'm using this tool for are getting overwritten...
Thanks!

**Comment by norwoodj** [comment]
@raphstrebel totally. Not a use case I'd thought of, but perfectly reasonable, and easy to do. Gimme a few minutes

**Comment by norwoodj** [comment]
@raphstrebel, this is done. Look out for release v0.11.0 which I'll release later tonight with these changes.

**Comment by norwoodj** [comment]
This has been released in [v0.11.0](https://github.com/norwoodj/helm-docs/releases/tag/v0.11.0)

**Comment by raphstrebel** [comment]
Great! thank you! :smile:
