### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by eddycharly** [norwoodj/helm-docs#35]
Would you be ok to release docker images ?
`goreleaser` supports [building and pushing docker images](https://goreleaser.com/docker/).

It would be useful to integrate in a CI pipeline, to ensure the doc is up to date.

Thanks.

**Comment by norwoodj** [comment]
Hey @eddycharly , sorry for the slow merge. Thanks for the contribution. Image is now available at https://hub.docker.com/r/jnorwood/helm-docs

**Comment by eddycharly** [comment]
Beautiful, thanks a lot 👍
