### ISSUE TITLE
Unable to generate README with Values injection into template files

### ISSUE THREAD

**Issue by wanderleyteixeira** [norwoodj/helm-docs#37]
We have `values.yaml` template and additional `values-<env>.yaml` per environment.
To install the chart, a YAML file that specifies the new values and overwrite the above default parameters are provided per environment:

`helm install --name someapp -f values=values-qa.yaml stable/someapp`

In this case, `values-qa.yaml` contains values that overwrite default `values.yaml`. When we run `helm-docs` it only reads `values.yaml` and output the default chart values, without the `qa`. Need ability to pass `values` like helm to output proper chart values table.

**Comment by eddycharly** [comment]
I don't think there is an option to create doc for files other than `values.yaml`.

All the configuration should exist in `values.yaml` anyway, and the generated doc should be complete.

The `values-qa.yaml` should only be there to provide the values corresponding to the specific `qa` environment, and therefore it out of the scope of the helm chart docs i think.

**Comment by wanderleyteixeira** [comment]
@eddycharly That definitely makes more sense. Thanks.
