### ISSUE TITLE
Does it support for windows operating system

### ISSUE THREAD

**Issue by rajurh** [norwoodj/helm-docs#51]
Documention doesn't show anything related to Windows OS. Is it supported on windows os or with subsystem on Linux?

**Comment by eddycharly** [comment]
Hi @rajurh , you should be able to `GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs` on windows if you have `golang` installed.

Another option would be to run it in docker `docker run --rm -v "$(pwd):/helm-docs" jnorwood/helm-docs:latest`.

**Comment by sc250024** [comment]
The GoReleaser file (https://github.com/norwoodj/helm-docs/blob/master/.goreleaser.yml) can be configured to create Windows `exe` files.

**Comment by norwoodj** [comment]
Hey @rajurh looks like this is doable. Will try to make this happen if I ever get the time
