### ISSUE TITLE
Repository Maintenance/Cleanup

### ISSUE THREAD

**Issue by DirtyCajunRice** [norwoodj/helm-docs#55]
Het @norwoodj. I saw you were having some personal issues via [this comment](https://github.com/norwoodj/helm-docs/pull/47#issuecomment-674906974) and hope all is well. I would be more than happy to help maintain this repo and help clean up some of the legacy code/ci that exists (e.g. old cobra design and deprecated goreleaser config). I plan to use helm-docs for the ever growing [k8s@home charts repo](https://github.com/k8s-at-home/charts) as well as a few other projects. If you would be more comfortable with me cloning the repo to preserve commits and starting in a new repository with attribution thats fine too!

Thanks!

**Comment by norwoodj** [comment]
Hey @DirtyCajunRice, I really appreciate the offer. There's tons of tech debt in this repo that needs cleaning up yes. The thing you can do to help most would be to review and submit pull requests. I simply don't have the time or capacity to keep up with all the issues that come in.

Please do start with a fork. I Will try to be better about getting to pull requests more quickly too

**Comment by norwoodj** [comment]
I've closed this for now. Feel free to open more specific issues and I'll take a look at them
