### ISSUE TITLE
Create homebrew tap for helm-docs

### ISSUE THREAD

**Issue by norwoodj** [norwoodj/helm-docs#6]
In order to make it easier for folks to install helm-docs, we should add a homebrew tap so that one can simply `brew install` the tool.

**Comment by sc250024** [comment]
I can actually do that, I've authored a couple of formulas now

**Comment by norwoodj** [comment]
Oh @sc250024, yeah, feel free. The [goreleaser](https://goreleaser.com/homebrew/) tool I've been using for releases has functionality for doing this automatically, so I was gonna try and figure out how to make that work. That being said, I've never done this before, so if you know how, feel free to contribute
