### ISSUE TITLE
Can I explicitly ignore a field?

### ISSUE THREAD

**Issue by mjpitz** [norwoodj/helm-docs#71]
There are a few fields I don't want to show up in my README. Is there a way to explicitly ignore or exclude a field?

**Comment by norwoodj** [comment]
There is not at present, but I think this is a reasonable ask. I can envision a flag (that can be repeated) like `--skip-values deployment.replicas` or similar. I can implement this when I get more time, (I'm very busy with my real job at present). Please feel free to submit a PR though.

**Comment by mjpitz** [comment]
No worries! I'll try and pull something together when I have a minute. Just wanted to make sure I wasn't missing something.

**Comment by Pothulapati** [comment]
👍 on this feature request! Would be useful for my use-case too!

**Comment by K1Hyve** [comment]
Would be good if this was implemented the same way as Bitnami's readme-generator-for-helm that you can specify fields to skip in the `values.yaml` itself.
https://github.com/bitnami-labs/readme-generator-for-helm#metadata

This would scale better when generating docs for multiple charts compared to using `--skip-values` flag.

**Comment by sheisnicola** [comment]
@K1Hyve @Pothulapati @mjpitz I needed something similar to this as well, but was able to implement it by generating the table myself in a custom template (I provide an example in an unrelated enhancement request I just raised here https://github.com/norwoodj/helm-docs/issues/107).

**Comment by j-buczak** [comment]
PR for this: Add option for ignoring values #141

**Comment by Anticom** [comment]
> There is not at present, but I think this is a reasonable ask. I can envision a flag (that can be repeated) like --skip-values deployment.replicas or similar. I can implement this when I get more time, (I'm very busy with my real job at present). Please feel free to submit a PR though.

I'd prefer configuring which values to skip via a special doc comment directive rather than a flag for helm-docs cli. My reasoning / use case is setting some values on sub chart's values. Since those are (hopefully) documented in the referenced chart, it would be superflous to have documentation for those overrides generated in my chart.

Alternatively the `--skip-values` flag either would have to work recursively or it would have to support globbing patterns. Otherwise I'd have to specify a huge set of values to be ignored / skipped.

**Comment by j-buczak** [comment]
@Anticom doc directive is already merged. It's documented here: https://github.com/norwoodj/helm-docs#ignoring-values

I don't know what are the plans for `--skip-values` flag. I can envision a case when it's useful, but I don't know what  are the plans for this. 

@norwoodj As original question/feature request is resolved, I would close this issue.

**Comment by Anticom** [comment]
> doc directive is already merged. It's documented here: https://github.com/norwoodj/helm-docs#ignoring-values

Oh, I've totally missed that. Thanks for the heads-up! 🚀
