### ISSUE TITLE
Template lookup should not fail if a template is not found

### ISSUE THREAD

**Issue by sagikazarmark** [norwoodj/helm-docs#77]
Currently if a template is not found the template lookup:
- stops looking up further templates
- returns the default template

This is somewhat counterintuitive to me, because helm-docs can be used to generate README files for multiple charts. Having custom per-chart overrides sounds like a perfectly valid use-case.

My suggestion is:

- if a template cannot be found continue template lookups (log the fact)
- load the default template if a template lookup fails (for backwards compatibility)

I'd be happy to provide a PR.

**Comment by norwoodj** [comment]
I think this makes a lot of sense. I'd be happy to review and merge a PR if you provided one. I unfortunately don't have time to do much work on this repository myself at the moment.
